-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 14:50:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newsconcursos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newsconcursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newsconcursos` DEFAULT CHARACTER SET utf8 ;
USE `newsconcursos` ;

-- -----------------------------------------------------
-- Table `newsconcursos`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`perfil` (
  `idPerfil` INT NOT NULL,
  `nomePerfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NULL,
  `ftUsuario` VARCHAR(45) NULL,
  `dtNascimento` DATE NULL,
  `CPF` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senhaUsuario` VARCHAR(45) NULL,
  `situacaoUsuario` VARCHAR(45) NULL,
  `perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_perfil_idx` (`perfil_idPerfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_idPerfil`)
    REFERENCES `newsconcursos`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`concurso` (
  `idConcurso` INT NOT NULL AUTO_INCREMENT,
  `tituloConcurso` VARCHAR(45) NULL,
  `dtAbertura` DATE NULL,
  `dtEncerramento` DATE NULL,
  `nivel` VARCHAR(45) NULL,
  `areaConcurso` VARCHAR(45) NULL,
  PRIMARY KEY (`idConcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `dtCadastroMaterial` DATE NULL,
  `nomeMaterial` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `tipoMaterial` VARCHAR(45) NULL,
  `concurso_idConcurso` INT NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_material_concurso1_idx` (`concurso_idConcurso` ASC) ,
  CONSTRAINT `fk_material_concurso1`
    FOREIGN KEY (`concurso_idConcurso`)
    REFERENCES `newsconcursos`.`concurso` (`idConcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`assinatura` (
  `idAssinatura` INT NOT NULL AUTO_INCREMENT,
  `tipoAssinatura` VARCHAR(45) NULL,
  `validade` INT NULL DEFAULT 0 COMMENT 'Validade e a quantidade de dias do pacote\nmensal 30 dias\nsemestral 180 dias\nanual 365',
  `valorAssinatura` DECIMAL(13,2) NULL DEFAULT 0,
  PRIMARY KEY (`idAssinatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `dtPagamento` DATE NULL,
  `valorTotal` DECIMAL(13,2) NULL DEFAULT 0,
  `tipoPagamento` VARCHAR(45) NULL,
  `assinatura_idAssinatura` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `dtLimite` DATE NULL COMMENT 'A dtLimite e igual a validade da assinatura(quantidade de dias) somada a data de pagamento ',
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_pagamento_assinatura1_idx` (`assinatura_idAssinatura` ASC) ,
  INDEX `fk_pagamento_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_pagamento_assinatura1`
    FOREIGN KEY (`assinatura_idAssinatura`)
    REFERENCES `newsconcursos`.`assinatura` (`idAssinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `newsconcursos`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`usuario_concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`usuario_concurso` (
  `usuario_idUsuario` INT NOT NULL,
  `concurso_idConcurso` INT NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`, `concurso_idConcurso`),
  INDEX `fk_usuario_has_concurso_concurso1_idx` (`concurso_idConcurso` ASC) ,
  INDEX `fk_usuario_has_concurso_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_usuario_has_concurso_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `newsconcursos`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_concurso_concurso1`
    FOREIGN KEY (`concurso_idConcurso`)
    REFERENCES `newsconcursos`.`concurso` (`idConcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsconcursos`.`usuario_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsconcursos`.`usuario_material` (
  `usuario_idUsuario` INT NOT NULL,
  `material_idmMaterial` INT NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`, `material_idmMaterial`),
  INDEX `fk_usuario_has_material_material1_idx` (`material_idmMaterial` ASC) ,
  INDEX `fk_usuario_has_material_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_usuario_has_material_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `newsconcursos`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_material_material1`
    FOREIGN KEY (`material_idmMaterial`)
    REFERENCES `newsconcursos`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
